### ISSUE TITLE
cannot download dataset from the link provided

### ISSUE THREAD

**Issue by Hanser14Forever** [yuchenlin/OpenCSR#4]
MEGA:The file you are trying to download is no longer available
This could be due to the following reasons:
The file has been removed as it violated our Terms of Service.
Invalid URL - the link you are trying to access does not exist.
The file has been deleted by the user.

**Comment by yuchenlin** [comment]
Thanks for the issue. Moved to here: https://github.com/yuchenlin/OpenCSR/tree/main/drfact_data/datasets
